### PR TITLE
fix: Treemap tests tech stack requirements and refactoring

### LINKED ISSUE #247: Treemap Diagram tests: add tech stack requirements and clean up code
#### Issue Description
This is Phase II of improving all the tests in this project. The following needs to be completed for each test suite:
- Add the tech stack requirements. See the Drum Machine tests for an example of a tech stack. Note that the tech stack will differ between the Front End Library assignments and the Data Visualization assignments.
- Make sure every test is accurate. Sometimes the tests say that they are checking for something, but there is no corresponding assertion that does what the test says. If the test description is wrong, you can just fix the description. But usually the test description is correct and it was just difficult to complete, so it was left as-is. In this case, try to figure out a way to fix the test to do what the description claims.
- Make sure the tests describe a step by step way of completing the project. Sometimes essential requirements have been missed. Or requirements might be out of order. Or a complex requirement can be broken up into multiple requirements. 
- At this point in the project it is better to be specific and that the tests describe *one way* of implementing the assignment. We are not trying to accommodate every possible solution a Camper could come up with. What we want instead is a series of requirements that lead the Camper step-by-step to code that is quite similar to each example project (https://codepen.io/collection/npZPmR/).
- If you are still confused about what needs to be done, please leave a comment for @tchaffee or @tbushman. You can also review recent PRs for Tribute Page, Survey Form, Product Landing, Technical Documentation, Personal Portfolio, Random Quote Machine, or Markdown Previewer, all of which have already been completed.

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #247 

#### Description

- Added tech stack requirements for D3 Treemap tests.
- Created new function hasUniqueColorsCount to eliminate duplicate code.
- Refactored all the D3 Treemap tests to make sure the wording and code is accurate. Also fixed some bugs, especially regarding the test about the area of the tile reflecting the data values. That test was not even working and would always pass even if the tile sizes were wrong.

### CODE REVIEW

File: src/utils/element-utils.js [hunk 1]
```diff
@@ -19,3 +19,30 @@ export function clickButtonsById(buttonIds) {
...
+  let uniqueColors = [];
+
+  // Use a loop instead of 'foreach' so we can return early.
+  for (let i = 0; i < elements.length; i++) {
+    let color = elements[i].style.fill || elements[i].getAttribute('fill');
+
+    // Make sure the color contains an actual value instead of something like
+    // null or undefined.
+    // If the current color isn't in the uniqueColors arr, push it.
+    // TODO: Isn't this logic in another D3 test too? Maybe Choropleth?
```
Comment (tbushman) [inline src/utils/element-utils.js]: If you want to remove this comment, I'll submit a new PR for Choropleth ...

**Comment by tbushman** [comment]
Really well thought-out edits. LGTM :)

File: src/utils/element-utils.js (hunk 1 above)
Comment (tchaffee) [reply src/utils/element-utils.js]: @tbushman If you don't mind, go ahead and merge this and you can remove the comment with the PR for Choropleth.
