### PR TITLE
account for 0.5px axis width subtracted from each end of d3 axis

### LINKED ISSUE #70: D3 scatter plot - test #8 failing
#### Issue Description

Built this graph today but it's failing one test when it shouldn't be.

It's failing test number 8 of 15. I checked out the criteria for the test by visiting the test JS file [here](https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/1de9ee9c2350f4e1963bc061bba7ffc56221e4cc/build/bundle.js) and then did a little bit of debugging.

It turns out that my scatter plot fails the test because the sort function in the test page sorts my array of dots in descending order rather than ascending, which means it fails at the very first assertion. If you look at the code and the chart itself, though, it's clearly all in working order.

#### Your Code / Link to Your Pen

[Codepen link](http://codepen.io/tom-p-uk/full/jBbMqq/)

Code for the appropriate failing test:
```
it('8. The data-yvalue and its corresponding dot should align with the corresponding point/value on the y-axis.', function () {
	                var dotsCollection = document.getElementsByClassName('dot');
	                //convert to array
	                var dots = [].slice.call(dotsCollection);
	                FCC_Global.assert.isAbove(dots.length, 0, 'there are no elements with the class of "dot" ');
	                //sort the dots based on yvalue in ascending order
	                var sortedDots = dots.sort(function (a, b) {
	                    return new Date(a.getAttribute("data-yvalue")) - new Date(b.getAttribute("data-yvalue"));
	                });

	                //check to see if the y locations of the new sorted array are in ascending order
	                for (var i = 0; i < sortedDots.length - 1; ++i) {
	                    FCC_Global.assert.isAtMost(+sortedDots[i].cy.baseVal.value, +sortedDots[i + 1].cy.baseVal.value, "y values don't line up with y locations ");
	                }
	            });

```

### PR DESCRIPTION
**Pull request by tbushman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #70

#### Description

This new PR gives a 1px leeway on checking alignment to account for 0.5px offset on d3 axes and apparent difference in codepen's window and the regular window tests.

### CODE REVIEW

File: src/assets/alignmentD3Tests.js [hunk 1]
```diff
@@ -0,0 +1,376 @@
...
+var isFeatureAligned = function(featureCoord, axis, tickPxCur, tickPxNext) {
+  // Determine lower / higher coordinate size between two ticks
+  // This is to account for reverse tick order (see issue #70)
+  var minTickCoord = Math.min(tickPxCur, tickPxNext);
+  var maxTickCoord = Math.max(tickPxCur, tickPxNext);
+  // getMisalignmentCount checked whether the feature's attribute data-xvalue or
+  // data-yvalue is between (inclusive) two ticks' labeled values.
+  // If that is true, the feature's pixel coordinates should also be between
+  // (inclusive) the two ticks' axis coordinates.
+  return featureCoord >= (minTickCoord - 1) && featureCoord <= (maxTickCoord + 1)
```
Comment (tchaffee) [inline src/assets/alignmentD3Tests.js]: Could you please just document why you are adding and subtracting a pixel? Otherwise someone might try to fix it.

**Comment by tchaffee** [comment]
LGTM
