### PR TITLE
Fix/product video src

### LINKED ISSUE #353: Does not accept sourceSets...
#### Issue Description

I attempted to use a `<video id='video'><source src=''><source src=''></video>` and it rejected it. But this is the best practice. Test fails you if you don't use a src in the video (even if you have <source> as a child of the video).

#### Browser Information

Safari

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

``` javascript
const srcs = `<source type="video/webm" src="https://www.videvo.net/videvo_files/converted/2015_08/preview/Tiger.mp460597.webm"><source type="video/mp4" src="https://www.videvo.net/videvo_files/converted/2015_08/videos/Tiger.mp460597.mp4">`
const container = create({
  tag: 'main',
  id: 'info',
  className: 'container',
  innerHTML: `<video
  class="videoplayer" id="video"
  controlslist="nodownload"
  controls src="https://www.videvo.net/videvo_files/converted/2015_08/videos/Tiger.mp460597.mp4">${srcs}</video>`,
  parent: window.root
})
 
 
```

### PR DESCRIPTION
**Pull request by tbushman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #353, #327

### CODE REVIEW

File: src/project-tests/product-landing-page-tests.js [hunk 1]
```diff
@@ -121,10 +121,19 @@ export default function createProductLandingPageTests() {
           video.nodeName === 'VIDEO' || video.nodeName === 'IFRAME',
           '#video should be an <iframe> or <video> element '
         );
+        // To accommodate `<source>` elements within `<video>` elements
+        // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source
+        const sourceNode = video.hasChildNodes();
```
Comment (tchaffee) [inline src/project-tests/product-landing-page-tests.js]: This might need to be more robust. A `<video>` element can also have `<track>` children. And `<track>` elements can have a `src` attribute.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track

File: src/project-tests/product-landing-page-tests.js [hunk 2]
```diff
@@ -121,10 +121,19 @@ export default function createProductLandingPageTests() {
...
+        let videoSrc;
+        if (sourceNode) {
+          videoSrc = video.children[0].hasAttribute('src');
+        } else {
+          videoSrc = video.hasAttribute('src');
```
Comment (tchaffee) [inline src/project-tests/product-landing-page-tests.js]: It might be safer to make this the primary check? If the `<video>` element does have a `src` attribute, then you can skip any further checking?

File: src/project-tests/product-landing-page-tests.js (hunk 1 above)
Comment (tbushman) [reply src/project-tests/product-landing-page-tests.js]: check updated please.
