### PR TITLE
Fix/tech doc underscores

### LINKED ISSUE #100: Failing Tests # 4 and #11 on Technical Documentation Page Project
#### Issue Description

When I run the test on my page it claims I am failing 2 tests, #4 and #11. my code appears to meet these requirements but I cannot manage to get it to pass these tests.  

#### Browser Information

* Chrome, Version 58.0.3029.110 (64-bit) 
* Windows 7
* Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/Supertechie2010/pen/JNqKeg?editors=1100

### PR DESCRIPTION
**Pull request by tbushman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #100 

#### Description

The test uses a regex replace to remove leading / trailing spaces and convert the ellipses to an underscore with a note added to remind. Ellipses don't work in id tags in Chrome and Safari.

### CODE REVIEW

**Comment by tbushman** [comment]
The bundle.js has many diffs that seem related to jQuery version.

**Comment by tbushman** [comment]
Test includes replace functions for leading / trailing spaces and ellipses in headerText, with a reminder to replace ellipses with an underscore in id tags.

**Comment by no-stack-dub-sack** [comment]
@tbushman would you be able to squash your commits before we merge this?

**Comment by tbushman** [comment]
@no-stack-dub-sack Oh dang, I wanted to keep them separate. The three PRs address three separate issues. I was using branches on a fork. Am I doing this correctly?

**Comment by tchaffee** [comment]
@tbushman I now have a PR that updates the bundle.js. If we can merge that PR, and then you rebase over master, it will be much clearer which changes to bundle.js are from your commit.

File: src/project-tests/technical-docs-tests.js [hunk 1]
```diff
@@ -59,7 +59,7 @@ export default function createTechnicalDocsPageTests() {
                     
                     const headerText = mainSections.map((el, i) => {
                       FCC_Global.assert.isAbove(el.firstElementChild.innerText.length, 0, 'All headers must contain text ')
-                      return [][i] = el.firstElementChild.innerText.replace(/\s/g, '_');
+                      return [][i] = el.firstElementChild.innerText.trim().replace(/^\s/g, '').replace(/\s$/g, '').replace(/\s/g, '_').replace('...', '_');
```
Comment (tchaffee) [inline src/project-tests/technical-docs-tests.js]: There are a series of four replaces here, along with regular expressions. Could you put a comment above this line explaining what the code is doing so future developers (including yourself) save the time of re-parsing this every time?

File: src/project-tests/technical-docs-tests.js [hunk 2]
```diff
@@ -59,7 +59,8 @@ export default function createTechnicalDocsPageTests() {
                     
                     const headerText = mainSections.map((el, i) => {
                       FCC_Global.assert.isAbove(el.firstElementChild.innerText.length, 0, 'All headers must contain text ')
-                      return [][i] = el.firstElementChild.innerText.replace(/\s/g, '_');
+                      //remove leading / trailing spaces in headerText, replace all other spaces with underscores, and replace the ellipsis with an underscore.
+                      return [][i] = el.firstElementChild.innerText.trim().replace(/^\s/g, '').replace(/\s$/g, '').replace(/\s/g, '_').replace('...', '_');
                     });
```
Comment (no-stack-dub-sack) [inline src/project-tests/technical-docs-tests.js]: @tbushman @tchaffee so I don't think we need both `.trim()` and the regex here. Either or will work, but trim should be sufficient. If we were to use regex, we could simplify it into one regex instead of chaining 2 `.replace()`s for the trailing and leading spaces, and make sure it covers more than 1 space just to be safe:
```js
'   example   '.replace(/^\s+|\s+$/g, '');
'   example    '.trim();
```

both of these will yield the same result. So this is something that can and should be cleaned up. 

The same goes for the elipsis and the `\s` character. We can simplify this instead of chaining by using the regex OR operator `|`. 

The best solution here I think is:
```js
'   examples...are cool   '.trim().replace(/\s|\.\.\./g, '_'); //  => examples_are_cool
```
Try running this line in the browser console or on https://repl.it/languages/javascript and you'll see what I mean. 

It has been a while since I've touched this project so if there was another reason for doing it like this I'm all ears! Otherwise, I think this can be changed to reflect the above.

File: .gitignore [hunk 3]
```diff
@@ -48,4 +48,11 @@ local_test/css/*
...
-*.DS_Store
\ No newline at end of file
+*.DS_Store
+
+# textmate
+code_textmate
+code_textmate.tmproj
+
+# sass
+.sass-cache/*
```
Comment (no-stack-dub-sack) [inline .gitignore]: Also, what are the additions to the gitignore?

File: src/project-tests/technical-docs-tests.js [hunk 4]
```diff
@@ -59,7 +59,8 @@ export default function createTechnicalDocsPageTests() {
                     
                     const headerText = mainSections.map((el, i) => {
                       FCC_Global.assert.isAbove(el.firstElementChild.innerText.length, 0, 'All headers must contain text ')
-                      return [][i] = el.firstElementChild.innerText.replace(/\s/g, '_');
+                      //remove leading / trailing spaces in headerText and then replace all other spaces with underscores.
+                      return [][i] = el.firstElementChild.innerText.replace(/^\s+|\s+$/g, '').replace(/\s/g, '_');
```
Comment (no-stack-dub-sack) [inline src/project-tests/technical-docs-tests.js]: @tbushman ok, so a few things here:

- **first**: ultimately, I think the solution using `trim` is the best solution since it's more succinct and this first `replace` regex does the same thing. No need to use that when we have the built in function. I was just providing the regex by way of example to show that there was another way besides chaining the `replace` method. 

Let's change this to:
```js
el.firstElementChild.innerText.trim().replace(/\s/g, '_');
```

- **second**: what was the deal with replacing the elipsis? Not sure why we were doing this, but if there was a good reason to, we should still be doing it, but just accomplishing it in one `replace` method: e.g. `.replace(/\s|\.\.\./g, '_')`

- **finally** - it would seem that I introduced some poor code here. Returning an assignment from a function as I was doing here is poor practice, even though in this case it works. Let's do this instead:

```
let arr = [][i] = el.firstElementChild.innerText.replace(/^\s+|\s+$/g, '').replace(/\s/g, '_');
return arr;
```
for both this one and the function right below it. Feel free to change the assignment if we are going back to replacing the elipsis (though again, not sure where that came from in the first place).

Does this all make sense? If you need help on anything, feel free to hit me up on Gitter! Happy to help.

Thanks!

**Comment by no-stack-dub-sack** [comment]
@tbushman Also, why does this have the commit from the jquery updated?

**Comment by tbushman** [comment]
OK. fsr trim() wasn't catching cases in testing. Wait on this for me please.

**Comment by no-stack-dub-sack** [comment]
@tbushman hmmm, ok. Strange, but if it doesn't work, it doesn't work. It should, but the regex solution works as well, so if that works better on your local tests, than we can stick with that. Still wondering about the elipsis thing though. 

Anyway, take your time and no rush.

**Comment by tbushman** [comment]
@no-stack-dub-sack One of the tests I ran had an ellipsis in the id, and I was not thorough in establishing whether id tags could accommodate ellipses and made the wrong assumption. The issuer had changed the ellipsis to an underscore and was therefore not passing the test and I'm glad for these reviews. Thanks!

**Comment by no-stack-dub-sack** [comment]
@tbushman gotcha, ok no prob! So skip the elipsis, but we can go ahead with the other changes.

**Comment by no-stack-dub-sack** [comment]
Ok, cool - well the gitignore is no longer in the diff because we merged it in in the last PR. 

However, did you see my previous comment about fixing my poor code from when I first wrote this? Looking at it there's a few places where this could be done. Would you be comfortable making this fix? It's ok if not, we can just merge this in and I can do it later today.

**Comment by tbushman** [comment]
@no-stack-dub-sack I'll do it. Momento.

**Comment by tbushman** [comment]
OK.

**Comment by no-stack-dub-sack** [comment]
@tbushman I'm really sorry, totally my fault - I wasn't paying close enough attention yesterday. This is still poor code. I was trying to do a million things at once. Here are the 4 instances of `map` and what they should look like. I wrote this a long time ago and probably didn't have the best grasp on some of this at the time. The array assignments just aren't necessarry with the nature of `map`:

```js
const headerText = mainSections.map((el, i) => {
  FCC_Global.assert.isAbove(el.firstElementChild.innerText.length, 0, 'All headers must contain text ')
  return el.firstElementChild.innerText.trim().replace(/\s/g, '_');
});

const mainSectionIDs = mainSections.map((el, i) => {
  FCC_Global.assert.strictEqual(el.hasAttribute('id'), true, "Each 'main-section' should have an id attribute ")
  return el.id;
});

const headerText = classArray('main-section').map((el, i) => el.firstElementChild.innerText.trim());

const linkText = classArray('nav-link').map((el, i) => /[^\n\t\f\r\v]+/.exec(el.innerText)[0]); 
```
Can you find these and make the necessary replacements as shown above? Last change on this one, I promise.

**Comment by tbushman** [comment]
@no-stack-dub-sack OK.

**Comment by no-stack-dub-sack** [comment]
@tbushman Yes! Perfect. Thanks for your patience! Merging this in.
