### PR TITLE
Fix/portfolio anchors

### LINKED ISSUE #336: Weird Re-Loading Bug in the Personal Portfolio Project
#### Issue Description

Whenever I run the test suite in my portfolio project, it gets to 7/12 tests, then completely re-loads the page. I've tried taking out the nav (since I think it's getting hung up on the link following tests). I've tried displaying both custom dropbox menus, and I've set all links to `target="_blank"`

In all honesty, this is probably happening because this is a project I've been working on independently (before free code camp). So the code in general is kinda messy (sorry in advance). But I'm curious about exactly how it's breaking, so I know how to clean my code! :)

#### Browser Information

* Google Chrome, Version:  67.0.3396.62 (Official Build) 
* Operating System: Windows
* Device: Windows Surface Pro
* Coding Environment: Visual Studio Code

it is worth noting that I have a similar problem when I drop the code into codepen (instead of re-loading it turns into a blank page)

#### Link to Your Pen
https://codepen.io/thegouge/pen/QxjdEQ?editors=1100

### PR DESCRIPTION
**Pull request by tbushman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #336

#### Description

Ensure external links aren't clicked in the navbar tests. Click hashed hrefs only.

### CODE REVIEW

File: src/project-tests/portfolio-tests.js [hunk 1]
```diff
@@ -81,7 +81,11 @@ export default function createPortfolioTests() {
       it(`${reqNum}. The navbar should contain at least one link that I can
       click on to navigate to different sections of the page.`,
       function(done) {
+        // Filter anchors by location hash (don't click external links)
         const links = Array.from(document.querySelectorAll('#navbar a'));
+        links.filter(function(nav) {
```
Comment (tchaffee) [inline src/project-tests/portfolio-tests.js]: I'm not sure this is working the way you intend. I think `filter` does not change the original array. I think you have to do something like this:

```
links = links.filter(function(nav) {
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

File: src/project-tests/portfolio-tests.js [hunk 2]
```diff
@@ -146,9 +150,14 @@ export default function createPortfolioTests() {
         // Tests start here. We need a longer timeout for this test. 10 seconds
         // is enough to test about 10 nav links.
         this.timeout(10000);
+        // Filter anchors by location hash (don't click external links)
+        let anchors = Array.from(document.querySelectorAll('#navbar a'));
+        anchors.filter(function(nav) {
```
Comment (tchaffee) [inline src/project-tests/portfolio-tests.js]: Same as my comment above about needed to assign the result.

**Comment by tbushman** [comment]
@tchaffee Good catch. Thanks! I've tested this latest version on a few projects and it's ready.
