### PR TITLE
fix(tests): except minus operator intended as negative sign

### LINKED ISSUE #908: Calculator test conditions do not permit negative number multiplication
#### Issue Description

According to math, the following expression is valid:
-3*-3
The answer is 9.

According to the project requirements, however, -3*-3 becomes -6 because of the requirement "If 2 or more operators are entered consecutively, the operation performed should be the last operator entered."

This might make some aspect of the coding/testing easier, but it is wrong. A JavaScript calculator ought to work like a real calculator.

#### Your Code / Link to Your Pen
You can view this behavior in the example project
https://codepen.io/freeCodeCamp/full/wgGVVX

### PR DESCRIPTION
**Pull request by tbushman**
ISSUES CLOSED: #908

#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [ ] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.

- [x] Closes currently open issue: Closes #908

#### Description

@scissorsneedfoodtoo Once this is merged, the javascript calculator Codepen will need to be updated as well. Thank you. :)

### CODE REVIEW

File: src/projects/javascript-calculator/index.jsx [hunk 1]
```diff
@@ -14,6 +14,8 @@ const projectName = 'javascript-calculator';
 // VARS:
 const isOperator = /[x/+‑]/,
   endsWithOperator = /[x+‑/]$/,
+  multiOperators = /[x/+‑]{2,}/,
+  negativeSign = /[x/+]+[‑]$/,
```
Comment (ValeraS) [inline src/projects/javascript-calculator/index.jsx]:
```suggestion
  endWithNegativeSign = /[x/]‑$/,
```

File: src/projects/javascript-calculator/index.jsx [hunk 2]
```diff
@@ -98,10 +113,12 @@ class Calculator extends React.Component {
           formula: e.target.value !== '0' ? e.target.value : ''
         });
       } else {
+        const currPlusTarget = (this.state.currentVal + e.target.value);
         this.setState({
           currentVal:
             this.state.currentVal === '0' ||
-            isOperator.test(this.state.currentVal)
+            isOperator.test(this.state.currentVal) &&
+            !negativeException(currPlusTarget)
```
Comment (ValeraS) [inline src/projects/javascript-calculator/index.jsx]: `!negativeException(currPlusTarget)` always will be true, because of e.target.value is a number in this case.

File: src/projects/javascript-calculator/index.jsx [hunk 3]
```diff
@@ -56,6 +61,13 @@ class Calculator extends React.Component {
       if (endsWithOperator.test(expression)) {
```
Comment (ValeraS) [inline src/projects/javascript-calculator/index.jsx]:
```suggestion
      while (endsWithOperator.test(expression)) {
```

File: src/projects/javascript-calculator/index.jsx [hunk 4]
```diff
@@ -56,6 +61,13 @@ class Calculator extends React.Component {
...
         expression = expression.slice(0, -1);
       }
+      if (multiOperators.test(expression) &&
```
Comment (ValeraS) [inline src/projects/javascript-calculator/index.jsx]: Not needed. We should get the correct formula in this place.

**Comment by tbushman** [comment]
@ValeraS I remember when GitHub wouldn't tell you how many times I force-push. :) I got a little mixed up, but it's working.

File: src/projects/javascript-calculator/index.jsx (hunk 2 above)
Comment (tbushman) [reply src/projects/javascript-calculator/index.jsx]: Thank you.

**Comment by tbushman** [comment]
NVM it's not working ... bbiab

**Comment by ValeraS** [comment]
@tbushman I've made some changes, could you check it?

**Comment by tbushman** [comment]
@ValeraS Outstanding. :) Thank you! LGTM!
