### PR TITLE
Fix/scatterplot

### LINKED ISSUE #70: D3 scatter plot - test #8 failing
#### Issue Description

Built this graph today but it's failing one test when it shouldn't be.

It's failing test number 8 of 15. I checked out the criteria for the test by visiting the test JS file [here](https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/1de9ee9c2350f4e1963bc061bba7ffc56221e4cc/build/bundle.js) and then did a little bit of debugging.

It turns out that my scatter plot fails the test because the sort function in the test page sorts my array of dots in descending order rather than ascending, which means it fails at the very first assertion. If you look at the code and the chart itself, though, it's clearly all in working order.

#### Your Code / Link to Your Pen

[Codepen link](http://codepen.io/tom-p-uk/full/jBbMqq/)

Code for the appropriate failing test:
```
it('8. The data-yvalue and its corresponding dot should align with the corresponding point/value on the y-axis.', function () {
	                var dotsCollection = document.getElementsByClassName('dot');
	                //convert to array
	                var dots = [].slice.call(dotsCollection);
	                FCC_Global.assert.isAbove(dots.length, 0, 'there are no elements with the class of "dot" ');
	                //sort the dots based on yvalue in ascending order
	                var sortedDots = dots.sort(function (a, b) {
	                    return new Date(a.getAttribute("data-yvalue")) - new Date(b.getAttribute("data-yvalue"));
	                });

	                //check to see if the y locations of the new sorted array are in ascending order
	                for (var i = 0; i < sortedDots.length - 1; ++i) {
	                    FCC_Global.assert.isAtMost(+sortedDots[i].cy.baseVal.value, +sortedDots[i + 1].cy.baseVal.value, "y values don't line up with y locations ");
	                }
	            });

```

### PR DESCRIPTION
**Pull request by tbushman**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #70 

#### Description

New tests to detect if dots line up with axes. First, axis range is determined using the d attribute, split into moveto segments. Then, cx and xy values are iteratively compared as percentages of axis width / height to axis values). 
These new tests work on the FCC sample, and codepens by @sa-mm and @tom-p-uk .

### CODE REVIEW

File: src/project-tests/scatter-plot-tests.js [hunk 1]
```diff
@@ -67,10 +67,38 @@ export default function createScatterPlotTests() {
                 const sortedDots = dots.sort(function(a, b) {
                     return a.getAttribute("data-xvalue") - b.getAttribute("data-xvalue")
                 });
-
-                //check to see if the x locations of the new sorted array are in ascending order
-                for (var i = 0; i < sortedDots.length - 1; ++i) {
-                    FCC_Global.assert.isAtMost(+sortedDots[i].cx.baseVal.value, +sortedDots[i + 1].cx.baseVal.value, "x values don't line up with x locations ");
+                var xAxisQuery = document.querySelector('#x-axis path');
```
Comment (tchaffee) [inline src/project-tests/scatter-plot-tests.js]: If you put this whole section into a new function (something like `checkDotsAxisAlign`?) I think it would make the tests more readable and focused on what is being tested. Also, I would like to see more documentation because I cannot figure out exactly what the code is doing just by reading the code. A summary at the top of the new function, and then some line comments where it's not obvious what the code is doing.

File: src/project-tests/scatter-plot-tests.js [hunk 2]
```diff
@@ -67,10 +67,38 @@ export default function createScatterPlotTests() {
...
+                //x-axis path x coordinates from d
+                var xAxisLeft = xAxisQuery.getAttribute('d').split(',')[0].split('M')[1]
```
Comment (tchaffee) [inline src/project-tests/scatter-plot-tests.js]: Here's an example of code that isn't immediately apparent. What is attribute `d`? Why are we splitting it by the comma and then M? Even an example of the data this is supposed to parse would help. There are more lines like this, but I'm just going to leave this one comment.

File: src/project-tests/scatter-plot-tests.js [hunk 3]
```diff
@@ -84,9 +112,38 @@ export default function createScatterPlotTests() {
                     return new Date(a.getAttribute("data-yvalue")) - new Date(b.getAttribute("data-yvalue"));
                 });
 
-                //check to see if the y locations of the new sorted array are in ascending order
-                for (var i = 0; i < sortedDots.length - 1; ++i) {
-                    FCC_Global.assert.isAtMost(+sortedDots[i].cy.baseVal.value, +sortedDots[i + 1].cy.baseVal.value, "y values don't line up with y locations ");
+                var yAxisQuery = document.querySelector('#y-axis path');
```
Comment (tchaffee) [inline src/project-tests/scatter-plot-tests.js]: A lot of the code here looks very similar to what you did for the x-axis. Could the code be shared in a function? Or better, several small functions?

File: src/project-tests/scatter-plot-tests.js [hunk 4]
```diff
@@ -1,6 +1,109 @@
...
+        }
+    } else {
+        return {
+	        text: y.querySelector('text').innerHTML,
+	        px: y.getAttribute('transform').split(',')[1].split(')')[1]
+        }
+    }
+}
+
+//for given feature, get values and coordinates from feature attributes
```
Comment (tbushman) [inline src/project-tests/scatter-plot-tests.js]: In case this turns into a reusable function for other graphs, I've commented in an example.

**Comment by tbushman** [comment]
In the latest revision I'm using more general variables and closures with the aim of reuse-ability.

**Comment by tchaffee** [comment]
This looks much better. I still have some suggestions if you are interested in refactoring even more to make things simpler. But I think it would be a lot easier if we did a Skype call. I'm available most of today, or any time later in the week. Let me know.

**Comment by tbushman** [comment]
@no-stack-dub-sack In the latest commit, @tchaffee and I have put refactored alignment tests into their own module under assets. I'm using JSDoc for commenting because I think it may need additional refactoring and wanted to clarify what everything was doing. I also updated the scatter-plot-tests.js with the new formatting.

File: src/project-tests/scatter-plot-tests.js [hunk 5]
```diff
@@ -1,146 +1,287 @@
...
-            });
-
-            it('13. I can see a legend that has id="legend".', function() {
-                FCC_Global.assert.isNotNull(document.getElementById('legend'), 'There should be an element with id="legend" ');
-            });
-        });
-        
-        testToolTip(document.querySelectorAll('.dot'), "data-year", "data-xvalue")
+    describe('#Content', function() {
+      it('1. I can see a title element that has a corresponding id="title".',
```
Comment (tchaffee) [inline src/project-tests/scatter-plot-tests.js]: @tbushman These reformatting changes should be put in a separate PR. Otherwise it is hard to tell which changes are related to your new feature, and which are only related to re-formatting. 

It does make sense to correctly format the tests you changed. Which means this code will have inconsistent formatting. But that should be very temporary since as soon as we merge this the next step would be for you to submit another PR fixing the formatting for this entire file.

If that doesn't make sense, please feel free to reach out to me on Skype and we can talk about it.

**Comment by tbushman** [comment]
@tchaffee Thanks for all the help. OK, I think this is good to go, but I see there are merge conflicts I'm not clear on how to handle.

**Comment by tbushman** [comment]
@tchaffee In my next commit, I will change the test to compare pixel values only, removing the step to convert to percentage, and accounting for the 0.5px offset d3 adds to the ends of the axes. No merging yet. Thanks.

File: build/bundle.js [hunk 6]
```diff
@@ -20949,6 +20949,8 @@ var FCC_Global =
 
 	var _globalD3Tests = __webpack_require__(54);
 
+	var _alignmentTestsD = __webpack_require__(56);
```
Comment (tbushman) [inline build/bundle.js]: @tchaffee @no-stack-dub-sack Can someone tell me why webpack is truncating the name of alignmentTestsD3 to _alignmentTestsD and / or let me know if this is cause for concern?

Comment (marigerr) [inline build/bundle.js]: I believe it truncates modules names that end in a digit.   If you use `alignmentD3Test` it won't truncate.   I believe it does this because in situations where a 2nd variable is created in the bundle for example as _interopRequireDefault .   
```
var _jquery = __webpack_require__(1);
var _jquery2 = _interopRequireDefault(_jquery);
```
 The 2nd variable name will have incremented digit at end.   So they probably don't allow digits at end to avoid confusions there. 

If you keep the filname `alignmentTestD3.js`  , I don't think it would be a problem as the truncated name is just a variable name to reference the correct module/file.

But if change file name to `alignmentD3Test.js` could match `globalD3Test.js` naming style !

Comment (tbushman) [inline build/bundle.js]: Good point! :D Thanks @marigerr .

**Comment by tchaffee** [comment]
LGTM

**Comment by tchaffee** [comment]
LGTM
