### PR TITLE
Quote Machine: Small Improvements listed in the commit body.

### LINKED ISSUE #172: Make the Quote Machine tests more deterministic
#### Issue Description

The Quote Machine tests use an arbitrary timeout (currently 4 seconds) to wait for the initial quote and new quotes to load. On a slow network a Camper fetching from an API might see the test fails quite often. If there is a way to detect when the quote text changes without using an arbitrary timeout, that would be far better. To be clear, there should still be a timeout, but the timeout would be much longer.

Current logic:
1. Set timeout to a "guess" of how long it might take for a new quote to load. Our current "guess" is hard-coded to 4 seconds.
2. Wait that entire time. At the end check if a new quote is loaded.

Possible new logic:
1. Set the timeout to a reasonably large number like 10 or 20 seconds.
1. Check every 500 milliseconds if a new quote has loaded.
1. When a new quote has loaded, the test should pass immediately. This would also make the tests a lot faster in cases when a quote loads quickly.

Link to the official example CodePen:

#### Browser Information
All browsers and OSes.

#### Your Code / Link to Your Pen
Official CodePen example for this project:
https://codepen.io/freeCodeCamp/pen/qRZeGZ

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #172 

#### Description
- Moved the centering test to its own module. Hopefully it can be reused.
- Added the Technology Stack requirement.
- Added dynamic test numbering.
- Changed the timeout logic so the tests pass immediately when success is detected. This way is more deterministic and should eliminate the occasional failures we get with this test suite. In addition, the tests are now significantly faster.
- Used Promises everywhere applicable, instead of a mix of promises and 'done'.

### CODE REVIEW

**Comment by tchaffee** [comment]
@tbushman This has been rebased and is ready for review and / or merge.

File: src/assets/sharedTestStrings.js [hunk 1]
```diff
@@ -7,3 +7,13 @@ export const responsiveWebDesignStack = '1. You can use HTML, JavaScript, ' +
...
   'stacks like React. We will accept and try to fix all issue reports that ' +
   'use the suggested technology stack for this project. Happy coding!';
+
+export const frontEndLibrariesStack = '1. You can use any mix of HTML, ' +
+  'JavaScript, CSS, Bootstrap, SASS, React, Redux, and jQuery to complete ' +
+  'this project. You should use a frontend framework (like React for ' +
+  'example) because this section is about learning frontend frameworks. ' +
+  'Additional technoligies not listed above are not recommended and using ' +
+  'them is at your own risk. We are looking at supporting other frontend ' +
+  'frameworks like Angular and Vue, but they are not currently supported. ' +
```
Comment (tbushman) [inline src/assets/sharedTestStrings.js]: I'm pretty sure the tests work as-is with Angular projects, but this warning can't hurt.

Comment (tchaffee) [reply src/assets/sharedTestStrings.js]: As soon as we have example Angular projects to test against, we'll remove this.
