### PR TITLE
check element's placement in relation to viewport 

### LINKED ISSUE #134: N
#### Issue Description

Centered element not registered as centered on Quote Generator project.

Centered via Boostrap 3.3.7 col-xs-4 col-xs-offset-4

https://codepen.io/johnpyp/full/NgoeZX/

Fork that to reproduce.

#### Browser Information

* Browser Name, Version: Chrome 59.0.3071.115
* Operating System: Windows 7 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/johnpyp/full/NgoeZX/
 
```

#### Screenshot

image

### PR DESCRIPTION
**Pull request by marigerr**
check element's placement in relation to viewport instead of relation to parent element

#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #134 

#### Description

Changed layout test to use `getBoundingClientRect()` instead of `offsetLeft` to calculate elements placement in relation to viewport instead of parent element.   This change will allow Bootstrap offset class to be used to center element on page.    
In case scrollbar is present, allow 20px difference between right and left gap.   
Rawgit link  
https://rawgit.com/marigerr/testable-projects-fcc/fix/quote-machine-layout-test/build/bundle.js

### CODE REVIEW

File: src/project-tests/quote-machine-tests.js [hunk 1]
```diff
@@ -5,13 +5,11 @@ export default function createRandomQuoteMachineTests() {
...
-      const actualSideGap = centeredElement.offsetLeft;
-      const centeredElementWidth = centeredElement.clientWidth;
-      const gapExpectedWidth = (window.innerWidth - centeredElementWidth) / 2;
-      const delta = gapExpectedWidth - actualSideGap;
-      console.log(gapExpectedWidth, actualSideGap, delta);
-      return delta < 8.6 && delta > -3;
+      const centeredElementBounds = centeredElement.getBoundingClientRect();
+      const leftGap = centeredElementBounds.left;
+      const rightGap = window.innerWidth - centeredElementBounds.right;
+      console.log(window.innerWidth, leftGap, rightGap);
```
Comment (tchaffee) [inline src/project-tests/quote-machine-tests.js]: Could you please remove the `console.log`?

Comment (marigerr) [inline src/project-tests/quote-machine-tests.js]: Done!  Thanks for the review and merge :)
