### PR TITLE
fix: tests does not pass for "input" calculator buttons

### LINKED ISSUE #513: Javascript Calculators = and + tests are failing but shouldn't
#### Issue Description

Both "decimal" and "equals" buttons have the appropriate ids and values.
Visually and logically, seems that these tests should pass.
image
image

Seems like tests are failing because the two elements do not have their innerHTML property equal to the respective symbol ( . and = )

image

image

image

#### Browser Information

Google Chrome Version 64.0.3282
Ubuntu
Desktop

#### Your Code / Link to Your Pen

https://codepen.io/irinabrennen/pen/KvxBOd
 
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->

### PR DESCRIPTION
**Pull request by ValeraS**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #513

#### Description

add checks for an 'input' element as calculator button

### CODE REVIEW

File: src/project-tests/calculator-tests.js [hunk 1]
```diff
@@ -51,10 +51,11 @@ export default function createCalculatorTests() {
       it(`${reqNum}. My calculator should contain a clickable element
       containing an "=" (equal sign) with a corresponding id="equals"`,
       function() {
-        assert.isNotNull(document.getElementById(_eq));
+        let element = document.getElementById(_eq);
+        assert.isNotNull(element);
 
         assert.strictEqual(
-          document.getElementById(_eq).innerHTML,
+          element.localName === 'input' ? element.value : element.innerText,
```
Comment (tchaffee) [inline src/project-tests/calculator-tests.js]: Could you please change this to use `element.nodeName`?

`element.localName` is supposed to only work for XML docs. `element.tagName` looks a little better, but this Stackoverflow question has some comments explaining that `element.nodeName` is supported by the most browsers and is more standard. `element.nodeName` is supposed to return upper case, so you should also normalize it to always be lowercase, so you can compare with a lowercase value.

```
element.nodeName.toLowerCase() === 'input' ? element.value : element.innerText,
```

Obviously this should be changed everywhere, but I'm only making this comment.

https://stackoverflow.com/questions/254302/how-can-i-determine-the-type-of-an-html-element-in-javascript#254313
https://developer.mozilla.org/en-US/docs/Web/API/Element/localName
https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName
https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeName

File: src/project-tests/calculator-tests.js [hunk 2]
```diff
@@ -137,13 +138,14 @@ export default function createCalculatorTests() {
...
+        var element = document.getElementById(_dec);
         assert.isNotNull(
-          document.getElementById(_dec),
+          element,
           'id="decimal" is not yet defined '
         );
 
         assert.strictEqual(
-          document.getElementById(_dec).innerHTML,
+          element.localName === 'input' ? element.value : element.innerText,
```
Comment (tchaffee) [inline src/project-tests/calculator-tests.js]: Is there are reason to change from using `innerHTML` to `innerText`? Everywhere else in the code (example https://github.com/freeCodeCamp/testable-projects-fcc/blob/78310151942f56a99713d01abc9079ee8ffc3442/src/project-tests/calculator-tests.js#L181) we are using `innerHTML`.

I'm not opposed to this change as long as there is a good reason. More info about the differences here:

https://stackoverflow.com/questions/19030742/difference-between-innertext-and-innerhtml#19032002

https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

Let's discuss which you think is the best to use in this code and why. If we do decide to go with `innerText`, we should be consistent and make this change everywhere.

Comment (ValeraS) [reply src/project-tests/calculator-tests.js]: I think the best to use "innerText" in this code because we only want to check that a user sees some symbol on the screen, and not how it is coded.

This does not correspond to the issue, so I decided to propose it for the next PR.

Comment (tchaffee) [reply src/project-tests/calculator-tests.js]: @ValeraS I like `innerText` more too for this test suite. Mostly because `innerText` will not return text for invisible items, and the items should be visible for the tests to pass. But for this PR I would like to keep the code consistent. I would suggest either using `innerHTML` above for now and then submitting a separate PR to change all occurrences of of `innerHTML` to `innerText`. Or just changing everything in this PR. The cleanest approach would be two separate PRs. But it's a small change so doing everything in one PR is ok. Up to you.

**Comment by tchaffee** [comment]
LGTM! @ValeraS Thank you for your contribution. I hope we see you here more.
