### PR TITLE
fix(project-test): heatmap not detecting wrong values

### LINKED ISSUE #234: Heatmap data values test does not detect wrong values if they are string
#### Issue Description
Test 8 for the D3 Heat Map is supposed to ensure that the data-month attribute has values between 0 and 11 and it does not always do this. If the data-month attribute has a string value ('January' for example), the test will still pass. The test should be fixed to determine if the data values are numeric, and to fail if they are not.

The code can be fixed by adding a isNaN check to the `valuesAreBetween` function (near line 182), after converting the data item to a number:

```
function valuesAreBetween(min, max, data) {
  for (var i = 0; i < data.length; i++) {
    // Note the use of the unary add (plus sign) before the data element
    // to attempt to convert to a number.
    var item = +data[i];

    if (isNaN(item)) {
      return false;
    }

    if (item < min || item > max) {
      return false;
    }
  }
  return true;
}
```

#### Browser Information
N/A

#### Your Code / Link to Your Pen
https://codepen.io/tom-p-uk/pen/ZeQEaE

### PR DESCRIPTION
**Pull request by jnmorse**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #234 

#### Description

replaced with a forEach for data-month and data-year, then using
`assert.isAtLeast()` and `assert.isAtMost()` to check values. Thus
ensuring that only numerical values are considered.

### CODE REVIEW

File: src/project-tests/heat-map-tests.js [hunk 1]
```diff
@@ -169,33 +169,19 @@ export default function createHeatMapTests() {
...
-          valuesAreBetween(0, 11, cellMonths),
-          'Month data values should be between 0 and 11 '
-        );
-        assert(
-          valuesAreBetween(1753, 2015, cellYears),
-          'Year data values should be between 1753 and 2015 '
-        );
+          assert.isAtLeast(dataYear, 1753, 'data-year should be at least 1753');
+          assert.isAtMost(dataYear, 2015, 'data-year should be at most 2015');
+        });
```
Comment (tbushman) [inline src/project-tests/heat-map-tests.js]: @jnmorse A really great improvement. It provides the comparison between expected and actual values in the report so the student knows to change from string to index.

**Comment by tbushman** [comment]
@tchaffee I did review it. Go ahead and merge.  
  
I think the timeouts sometimes occur when tooltips are tested -- if the random location falls out of the viewport.

**Comment by tchaffee** [comment]
@tbushman Thanks for the tip about the timeouts.
