### PR TITLE
global-D3-tests rename and fix ESLint warnings

### LINKED ISSUE #192: globalD3Tests rename and pass ESLint
- Rename the file from globalD3Tests.js to global-D3-tests.js to make the naming consistent throughout the project.
- Make sure the code in the file passes ESLint tests.

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x] Working changes have been added to the build by running `npm run build`

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.

- [x] Closes currently open issue: Closes #192 

#### Description
- Renamed the globalD3Tests.js file per our naming conventions.
- Fixed ESLint warnings.

### CODE REVIEW

**Comment by tchaffee** [comment]
@tbushman I rebased this to resolve conflicts with master. It's ready for review and merge now.

File: src/assets/global-D3-tests.js [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+  JQuery's mouseevents don't work for non IE browsers in these tests.
+  This is a workaround to handle IE and non IE mouse events.
+*/
+function triggerMouseEvent(area, mouseEvent) {
+  var event;
+  if (document.createEvent) {
+     // Internet Explorer.
+     event = document.createEvent('MouseEvent');
+     // TODO: Provide a link where all the parameters for initMouseEvent are
+     // documented.
```
Comment (tbushman) [inline src/assets/global-D3-tests.js]: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent
