### PR TITLE
fix: Add check for localStorage support in browser

### LINKED ISSUE #1103: Add check for localStorage support in browser
If the user blocks third-party cookies, it blocks localStorage which we depend on for the tests. Right now we just silently fail.

I suggest adding a check in the `initTests` function to see that we have access to localStorage and warn the user if we do not.

### PR DESCRIPTION
**Pull request by lasjorg**
#### Pre-Submission Checklist

- [x] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
  
- [x] Closes currently open issue: Closes #1103

#### Description

This PR implements a check for access to localStorage and an alert message if access to localStorage is blocked. It is just a try/catch which is what Modernizr does for [testing localstorage support](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/storage/localstorage.js).

Here is a test page that show the alert. Block third-party cookies in the browser to see the alert.
https://codepen.io/lasjorg/pen/JjYbvxz

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -71,6 +71,24 @@ const shadow = (function attachShadow() {
...
 $(document).ready(function initTests() {
+  // Alert users about blocking third-party cookies.
+  // Blocking third-party cookies blocks localStorage, which we depend on.
+  try {
+    localStorage.setItem('fccTest', 'fccTest');
+    localStorage.removeItem('fccTest');
+  } catch (e) {
+    /* eslint no-alert: "off" */
+    alert(
+      'Test suites depends on access to localStorage. ' +
```
Comment (tbushman) [inline src/index.js:82]: 'Test suites depend on access...' (please make depends singular)

**Comment by tbushman** [comment]
@lasjorg Thanks for the working example. After the change, this LGTM!

File: src/index.js (hunk 1 above)
Comment (lasjorg) [reply src/index.js]: Done
